### ISSUE TITLE
Review of ANS student conference 2021 summary

### ISSUE THREAD

**Issue by robfairh** [robfairh/npre555-cp03#1]
This issue can be closed when @katyhuff has reviewed the following document:

[fairhurst-summary-v1.pdf](https://github.com/robfairh/npre555-cp03/files/5764612/fairhurst-summary-v1.pdf)

**Comment by katyhuff** [comment]
[fairhurst-summary-v1.pdf](https://github.com/robfairh/npre555-cp03/files/5816159/fairhurst-summary-v1.pdf)
